### ISSUE TITLE
Node support

### ISSUE THREAD

**Issue by freeqaz** [maierfelix/Iroh#5]
This library is awesome and I've started experimenting with how I can use this to build some dynamic analysis tools. My goal is to trace through requests in an Express app, which is all Node.

Currently, there are some shortcomings that prevent using this library in Node. There is an `npm` module published, though it seems to be outdated. The `package.json` also is missing an index path that allows a `require` statement to grab the code.

To fix this, something along the following lines should be done (which I might drop a PR for):
- Ensure module can be used via `npm install` and `import Iroh from 'irohjs';`
- Ensure `acorn` is installed as a `dependency` in `package.json` and also imported via Node syntax
  - `import acorn from 'acorn';`
- Support for "wrapping" a Node file. Currently, I have to use `fs` to grab the raw source code and then operate on that.
  - Additional tooling to support common Node cases would be helpful. I can give some more context around this, need be.

As I said, I might drop a PR to fix these. Wanted to highlight them before I sit down and foster a discussion. Let me know if you have any questions for me!

**Comment by maierfelix** [comment]
Hi there!

I have no idea how to link acorn as a dependency so I can do ``import acorn``, this caused the ``third_party`` folder in the root and the clunky ``build.js`` file. I'd love to get rid of all this!

Sadly [iroh](https://www.npmjs.com/package/iroh) is already a registered package name, so I decided to use ``irohjs`` for now - maybe the author of it is willed to transfer ownership.

I recently added a basic test to intercept ``require`` calls in theory [here](https://github.com/maierfelix/Iroh/blob/master/src/stage/debug.js#L319), so required code would get tracked too and can get linked to the main stage. However I'm not sure if that's the way to go or to let the user explicitly decide which code to track.

**Comment by maierfelix** [comment]
Update: the package author was so kind to transfer the ownership, [iroh](https://www.npmjs.com/package/iroh) can now be used

**Comment by maierfelix** [comment]
Added node.js support with https://github.com/maierfelix/Iroh/commit/f42f96a37de09f3d26c8047843ab2ef0f5b17a38
``npm install iroh`` should now work

**Comment by freeqaz** [comment]
Sweet, thank you for getting this sorted out!
